# Generated by Django 3.0 on 2021-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventmanager', models.CharField(max_length=20)),
                ('managercontact', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
