# Generated by Django 3.0 on 2021-06-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HallBooking', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='e',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
